#pragma once

#include <cstdint>

namespace violet
{
static constexpr std::uint32_t SURFACE_CACHE_FACE_COUNT = 6;

static constexpr float SURFACE_CACHE_TEXEL_DENSITY = 20.0f;
static constexpr std::uint32_t SURFACE_CACHE_ATLAS_RESOLUTION = 4096;
static constexpr std::uint32_t SURFACE_CACHE_PAGE_RESOLUTION = 128;
static constexpr std::uint32_t SURFACE_CACHE_PAGE_COUNT_X =
    SURFACE_CACHE_ATLAS_RESOLUTION / SURFACE_CACHE_PAGE_RESOLUTION;
static constexpr std::uint32_t SURFACE_CACHE_PAGE_COUNT_Y =
    SURFACE_CACHE_ATLAS_RESOLUTION / SURFACE_CACHE_PAGE_RESOLUTION;
static constexpr std::uint32_t SURFACE_CACHE_PAGE_COUNT =
    SURFACE_CACHE_PAGE_COUNT_X * SURFACE_CACHE_PAGE_COUNT_Y;

static constexpr std::uint32_t SURFACE_CACHE_FACE_MAX_RESOLUTION = 512;
static constexpr std::uint32_t SURFACE_CACHE_FACE_MAX_PAGE_COUNT_X =
    SURFACE_CACHE_FACE_MAX_RESOLUTION / SURFACE_CACHE_PAGE_RESOLUTION;
static constexpr std::uint32_t SURFACE_CACHE_FACE_MAX_PAGE_COUNT_Y =
    SURFACE_CACHE_FACE_MAX_RESOLUTION / SURFACE_CACHE_PAGE_RESOLUTION;
static constexpr std::uint32_t SURFACE_CACHE_FACE_MAX_PAGE_COUNT =
    SURFACE_CACHE_FACE_MAX_PAGE_COUNT_X * SURFACE_CACHE_FACE_MAX_PAGE_COUNT_Y;

static constexpr std::uint32_t SURFACE_CACHE_MAX_PAGE_COUNT = SURFACE_CACHE_PAGE_COUNT * 16;
} // namespace violet