#pragma once

#include "ui/controls/button.hpp"
#include "ui/controls/collapse.hpp"
#include "ui/controls/dock_area.hpp"
#include "ui/controls/dock_element.hpp"
#include "ui/controls/dock_window.hpp"
#include "ui/controls/font_icon.hpp"
#include "ui/controls/image.hpp"
#include "ui/controls/input.hpp"
#include "ui/controls/label.hpp"
#include "ui/controls/panel.hpp"
#include "ui/controls/scroll_view.hpp"
#include "ui/controls/tree.hpp"
#include "ui/controls/view.hpp"